<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSJXtRLL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSJXtRLL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSJXtRLL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSJXtRLL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSJXtRLL\App_KernelDevDebugContainer([
    'container.build_hash' => 'SJXtRLL',
    'container.build_id' => '67d4b11e',
    'container.build_time' => 1587406186,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSJXtRLL');
